### ISSUE TITLE
Add Trilobite API documentation

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/squid-py#153]
It would be necessary to document all the public methods implemented in the Trilobite release. The intention of this is to allow the developers to integrate this API without making necessary to go thru integration tests or similar.

@ttmc , could you define what is the best way to document the API to make this documentation available in the docs website?

**Comment by ttmc** [comment]
This issue is basically the same as https://github.com/oceanprotocol/docs/issues/44
See the comments there.

My current thinking is that we can start by using readthedocs.org to host the web-based documentation of squid-py, and in the future we can look into doing something fancy to get those docs into the docs.oceanprotocol.com site. That's not trivial because readthedocs takes care of things like multiple versions, search, and inter-page linking.

Python developers are used to seeing API docs on readthedocs.org so this shouldn't cause a great disturbance in the Force.

**Comment by ttmc** [comment]
Status update:

- The squid-py API docs are being automatically generated and hosted on ReadTheDocs at https://squid-py.readthedocs.io/en/latest/
- Currently only the latest version (i.e. the HEAD of the `develop` branch) of the docs are there but we can have other versions there in the future
- We're not linking to the ReadTheDocs docs from anywhere yet, because they aren't really complete or useful yet. Once there are more docstrings, they will be more useful.

**Comment by eruizgar91** [comment]
Done!

**Comment by ttmc** [comment]
A follow-up note: The squid-py docs _are_ now being linked-to from the official Ocean Protocol Docs site. For example, see https://docs.oceanprotocol.com/references/introduction/
