### ISSUE TITLE
More unit test coverage (understand the current coverage)

### ISSUE THREAD

**Issue by JohnBDB** [oceanprotocol/squid-py#185]

**Comment by aaitor** [comment]
@ShishKabab , @eruizgar91 , @ssallam , can we define a realistic unit tests coverage percentage to achieve in the scope of this task, taking into account the current coverage?

**Comment by eruizgar91** [comment]
Currently we are having an 85% that I think that it would be a good number to stay up. This value is achieved with the combination of unit tests and integration tests. Obviously we need to improve the unit test coverage, because most of the current test are integrated, but IMHO I think that we should do it in the functions that are squid-py logic more than in invest a big effort mocking for instance Web3. What do you think?

**Comment by ShishKabab** [comment]
If the integration tests really cover everything that might realistically go wrong, I'd say to take things slowly and take the opportunity to write unit tests whenever functionality is extended (and really take this seriously when accepting PRs!) As for mocking efforts, in the unit tests you can just use the dependency injection utility and specify the return values you expect, and keep the actual testing of Web3 in the integration tests.

**Comment by ssallam** [comment]
Sounds good, closing this as tests will be added gradually.
