### ISSUE TITLE
External services as repositories

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/squid-py#211]
Treat the external services as repositories.
For example:

Metadata -> MetadataStore/Serializer -> MetadataProvider -> http://aquarius...
DID -> DIDStore/Serializer -> Web3Provider -> DIDRegistry.sol
Agreements -> AgreementStore/Serializer -> Web3Provider -> ServiceExecutionAgreement.sol
...
and so on

In essence we can simply have a set of models, with different backend providers and dedicated serializers converting from provider to model and vice versa.

**Comment by diminator** [comment]
also see 
https://github.com/oceanprotocol/squid-js/blob/develop/src/aquarius/AquariusProvider.ts
https://github.com/oceanprotocol/squid-js/blob/develop/src/brizo/BrizoProvider.ts
etc...

**Comment by eruizgar91** [comment]
Can we close this issue @ssallam ?

**Comment by ssallam** [comment]
squid-py has been updated to use similar providers as in squid-js. 

This will likely change as a new design is recommended in another issue (by Vincent) to eliminate anti-patterns from both squid-js and squid-py so that we can have a more maintainable code base which reduce maintenance cost and make it easier to extend and add more features.
