### ISSUE TITLE
Register function on OceanMarket.sol requires 32 hex. We specify DID with more chars (did:op:...)

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#49]
## Expected Behavior

Register on-chain

## Current Behavior

DDO specifies DID in the 'id' field. 

DDO sample has 16 chars. (needs to be 32). 

Squid-py **Asset** class has multiple places where the DID is specified (.asset_id, DDO). 

### Possible Solution

Unify the DID location in Asset. Add a validation method.

**Comment by ttmc** [comment]
An Ocean Protocol DID string (i.e. the value of "id" in a DDO) should start with "did:op:" and end with 64 hex characters (0-9 and a-f). It takes 64 hex characters to represent a bytes32 because it takes two hex characters to represent each byte.

Reference: https://github.com/oceanprotocol/OEPs/tree/master/7#how-to-compute-a-did

Note: Only the bytes32 part needs to be stored on-chain, because it should be clear from context that the thing being stored is the bytes32 part of an Ocean Protocol DID.

**Comment by billbsing** [comment]
It's a text to byte conversion issue..

I have assumed that in the ```Asset``` class and within the testing suite, the ```asset_id``` is in the format of 64 character hex string, with **no leading '0x'**.

So the method ```generate_did``` and ```assign_did_from_ddo``` all assign an ```asset_id``` of up to 64 hex chars.

So therefore the ```asset_id``` validation needs to make sure that it is in the format of  ```re \[0-9a-f]{1,64}\```, and like wise the DID can be  ```re \^did:op:[0-9a-f]{1,64}\```, ( 7-51) chars.

The actual calling any smart contract, the ```asset_id``` is converted to 32 bytes ( allowing 2 hex chars per byte).

So as a result all DID's will have a maximum text length of 71 characters for the _did:op:xxx64xx_ to produce a 32 byte value once the DID header is removed and the hex string is converted to bytes.

If the DID is _did:op:1_, then the ```asset_id``` will be converted to  0x00000000000000000000000000000001 in 32 byte format.
