### ISSUE TITLE
Explicit configuration

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#63]
## Expected Behavior

More explicit configuration needed: if I pass in a config file path, then no defaults should be used. If something is missing, then it should fail early and clearly.  

## Current Behavior

Currently passing config file into Ocean is not robust, having to dig into debugger to find out that my URL is localhost when I want to use k8s! 

### Possible Solution

defaults should be explicitly stated by either a @classmethod like .from_defaults() or a flag use_defaults=true.  

?

**Comment by MarcusJones** [comment]
I think the config is even broken, it doesn't find aquarius.url!? 

```
    @property
    def aquarius_url(self):
        return self.get(self._section_name, NAME_AQUARIUS_URL)
```

`_section_name = ???` here?

**Comment by ttmc** [comment]
Requiring the explicit setting of every configuration setting (if there is a config file) seems a bit draconian. The reason for having default variables is so you only have to explicitly set the ones that you want to change.

That said, I do like the idea of forcing explicitness. If you want to go that route, then it would be nice to provide a default config file where all the configuration settings are set to their default values (not blank). Then the user only has to change the ones they care about.

**Comment by MarcusJones** [comment]
I propose something like;

```python
@classmethod
self.from_defaults()


@classmethod
self.from_ini_file()
```

**Comment by billbsing** [comment]
Why are we using a config file for a library? 

Maybe at the moment we need a config file, since we have quite a few contract addresses to resolve, but in the future when things get a bit more stable these should be semi permanently already assigned in the keeper-contract pypi .

We may resolver these errors if we got the library to actually accept individual config information, instead of one filename.

So it's just

1. keeper_url
2. aquarius_url
3. brizo_url
4. gas_limit

I can understand to have a set of default values, but probably best to keep them within the library, instead of a separate file to maintain outside the library.

I also noticed that since squid-py uses a config file, aquarius passes all config data over to squid-py.
Which I think is not a good thing, since aquarius is a server/daemon process and should manage it's own config file. Instead of using squid-py as a config file management library.

**Comment by billbsing** [comment]
I raised an issue about this #29, and add in  a fix so that we can use the ```ocean.__init__``` instead of  using a config file ( which has now been remove, sigh.. ) . I also raised an issue in [aquarius #68](https://github.com/oceanprotocol/aquarius/issues/68), so that we can move the aquarius to use it's own config file, instead of using the squid-py config class.

**Comment by MarcusJones** [comment]
I just want to cleanly and robustly set multiple configurations in Mantary: 
- various local docker images in different versions
- different versions in the Kubernetes clusters which are on a different update schedule
- different config in Kovan, mainnet
- whatever environment in Travis needs to be connected for testing

Yes, the library should have no config file. The client has the config file (or whatever way they want to pass in the params). This is why we have the deploy.sh script, so that clients create their own configurations as they wish. 

Currently, the Ocean class is just aggregating the smart contract Web3 instances and the aquarius server. It just passes on params to Keeper and Aquarius. +1 on **kwargs or dictionary. 

Propose to use ocean.__init__ to accept **kwargs, and implement something like 

```
@classmethod
self.from_ini_file()
```

**Comment by billbsing** [comment]
I was thinking that we would move the config file processing over to the command line and testing folder to be really separate away from the library. 

One possible solution, is to pass the contract addresses as environment variables, from the deploy.sh script. But since the deploy.sh is almost the same across over projects, I do not think it's justifiable to change this just for squid-py.

If as a Data Scientist user you think it's useful to use config files to setup the library then yes certainly add it in.

**Comment by MarcusJones** [comment]
Running into this again today! 
I agree that config is generally in separate library, but for unit testing, we do have this config in the repo

Currently, in [Mantaray](https://github.com/oceanprotocol/mantaray), I am switching between kubernetes deployed endpoints, and local with ocean_start.sh, or docker-compose etc. The local deployment requires the `wait_migrate` script, which copies the ABI's into the *project* folder, while the k8s deployment will rely on ABI in the *environment* (correct?). 

So this requires currently copying the ABI's from the project into the environment. 

Furthermore, we should add some debug logging messages to express what actual ABI's are being used, I can imagine a case where the project ABI's are used without anyone realizing. 

@ssallam Thoughts? And how to proceed with config once we are on kovan?

**Comment by billbsing** [comment]
I was hoping once the keeper contracts are more stable we could move the ABI's into a python module, and so get the squid-py to be loaded in the ABI's directly from PyPi.

I had a branch in squid-py that was called 'contract-builder' that did the packaging of the necessary ABI's into a module as auto loading JSON strings, I can move this over to the keeper-contracts repo and have it built into PyPi.

see [contract_data.py](https://github.com/oceanprotocol/fishpond/blob/develop/ocean/contract_data.py)

The problem with passing config items over is that we now have a load more options that we **must** provide to get squid-py working, especially after `secret store` we know have another +5 items.

storage_path
secret_store_url
partiy_url
parity_address
parity_password

So at the moment I think we should provide a config file and/or parameters for the library.

Not sure what the defaults should be:
+ all '' _empty_ and so invalid  and the library will not work with any test, 
or 
+ all 'localhost' where a local version would possibly work ?

**Comment by MarcusJones** [comment]
Bump and ref: https://github.com/oceanprotocol/ocean/issues/233

**Comment by ssallam** [comment]
`Ocean` now accepts a `config` instance, no more file/dict accepted.
Let's have a meeting to discuss what is necessary to make the config class more user friendly.
