### ISSUE TITLE
PyPI deployment needs dependencies specified

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#65]
## Current Behavior

pip install squid_py 
import squid_py
-> ModuleNotFoundError: No module named 'web3'

**Comment by ttmc** [comment]
The same issue is/was happening with `ocean-aquarius`. My pull request https://github.com/oceanprotocol/aquarius/pull/95 from yesterday tries to resolve it by putting the dependencies/requirements in `setup.py` (which is what `pip install ...` reads).

Note: For a _library_ like `squid_py`, I think you can relax the version values a bit (e.g. `package_name~=a.b.c` rather than `package_name==a.b.c`). Applications like `ocean-aquarius` need to be more strict, to ensure more predictable behaviour on installation.
