### ISSUE TITLE
Change Asset __init__ parameters

### ISSUE THREAD

**Issue by billbsing** [oceanprotocol/squid-py#75]
## Expected Behavior

I'm not sure what we are going to do with the ```Asset.__init__``` parameters.
```python
class Asset:
    def __init__(self, asset_id=None, publisher_id=None, price=None, ddo=None):
````
we can remove everything except the ```ddo``` object, and make it a requirement to create the asset
```python
class Asset:
    def __init__(self, ddo):
```
The other variables:
1. asset_id - generated by the metadata and stored as the DID
1. publisher_id - should this be set else where in another class? Since we should be able to purchase the same asset multiple times
1. price - is usually decided when the asset is sent to brizio?

Also for the ```consume``` and ```purchase``` methods will we need the ```Ocean``` object?
so are we passing ```Ocean``` object in the ```Asset.__init__```?

**Comment by MarcusJones** [comment]
Agree that the asset_id is not needed since it is already contained inside the DDO. 

So far we are publishing the metadata with; 
`ocean.metadata.publish_asset_metadata(asset)`

And we register on-chain with;
`self.keeper.market.register_asset(asset, asset_price, publisher_acct.address)`

I created a wrapper method to conduct both of these actions in sequence;
`ocean.register()`

For me, it is cleaner to call these actions from `Ocean` class, and not pass around the Ocean class, keeper class, contracts, etc.  Ocean is basically aggregating *everything*, and serves as *the* main API for the Ocean stack, so it just never made sense to have an Asset purchase itself... by passing around the aggregated stack... 

MVC? 

My two cents, as this could be considered a departure from the unified squid API.

**Comment by MarcusJones** [comment]
I suppose this will also become more complicated with service level agreements OEP11!

**Comment by MarcusJones** [comment]
But then wouldn't the helper method in Ocean class be passing itself into the Asset class? 
```python
def ocean.register(self,asset):
    asset.register(self)
``` 
? 

This is what I was trying to avoid, it's just personally a strain on my comprehension when I see an Asset instance aggregating the entire Ocean stack... 

I agree the register terminology is a bit ambiguous, but I guess we can revisit in a few weeks.

**Comment by billbsing** [comment]
I was thinking more along the lines of doing this..
```python
def ocean.create_asset(self, metadata):
     return Asset.create_from_metadata(self, metadata)

def ocean.register(self, asset):
     asset.register()
```
or without bringing across the whole of ```ocean``` object, we can just pass the relevant sub objects needed for the asset to work  such as: keeper, web3 via the ```Asset.__init__```.

**Comment by billbsing** [comment]
The asset __init__ parameters was correct in merge #87
