### ISSUE TITLE
Ambiguous logging message

### ISSUE THREAD

**Issue by MarcusJones** [oceanprotocol/squid-py#84]
Each time you start squid-py, it shows `Failed to load configuration file. Using default configs`. ??

This comes from; 

https://github.com/oceanprotocol/squid-py/blob/f20d6877f7b7e707f9e262a8523aee2bb5ee18d8/squid_py/log.py#L32

Just remove this print statement...

**Comment by ttmc** [comment]
Oh! That exact line (`Failed to load configuration file. Using default configs`) appeared when I tried @billbsing pull request #73 to build docs using Sphinx. I thought it was a Sphinx message, but it didn't make any sense because the Sphinx config file (`conf.py`) was right where it was supposed to be. In other words, fixing this issue might also resolve that issue with pull request #73!

**Comment by MarcusJones** [comment]
Updated in PR #131  - 
Changed message to 'Using default logging settings.'
